#!/usr/bin/env bash
# This script displays information about subdomains of a given domain

# Function to display subdomain information
display_subdomain_info() {
    local domain="$1"
    local subdomain="$2"
    local record_type=$(dig "$subdomain.$domain" | awk '/^;; ANSWER SECTION:/{getline; print $4}')
    local destination=$(dig "$subdomain.$domain" | awk '/^;; ANSWER SECTION:/{getline; print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main script logic
if [ $# -eq 0 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
elif [ $# -eq 1 ]; then
    domain="$1"
    subdomains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${subdomains[@]}"; do
        display_subdomain_info "$domain" "$subdomain"
    done
elif [ $# -eq 2 ]; then
    domain="$1"
    subdomain="$2"
    display_subdomain_info "$domain" "$subdomain"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
