#!/usr/bin/env bash

file="/etc/nginx/sites-available/default"
redirect_code="return 301 https://github.com/vicksonian;"
sed -i "s@location \/ {.*@&\n\tlocation \/redirect_me {\n\t\t$redirect_code\n\t}@" "$file"

service nginx restart || /etc/init.d/nginx restart
