#!/usr/bin/env bash
# Installs nginx web server

apt-get update
apt-get install -y nginx
service nginx start
mkdir /etc/nginx/html
echo "Hellow World!" > /etc/nginx/html/index.html
echo "Page not found!" > /etc/nginx/html/404.html
echo "server {
	listen 80;
	listen [::]:80 default_server;
	root   /etc/nginx/html;
	index  index.html;
	location /redirect_me {
	return 301 https://www.linkedin.com/in/george-pußl;
	}
	error_page 404 /404.html;
	location = /404.html{
	root /etc/nginx/html;
	internal;
	}
}" > /etc/nginx/sites-available/default
service nginx restart
