#!/usr/bin/env bash
# This script installs and configures HAProxy as a load balancer

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
sudo touch /etc/haproxy/haproxy.cfg

# Configure HAProxy to use round-robin algorithm and distribute requests to web-01 and web-02
echo "frontend http_front" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "    bind *:80" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "    stats uri /haproxy?stats" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "    default_backend http_back" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "backend http_back" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "    balance roundrobin" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "    server web-01 100.24.236.225:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "    server web-02 [WEB-02-IP]:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart HAProxy
sudo systemctl restart haproxy
