#!/usr/bin/env bash
# Configure Nginx to listen on port 80

# Update Nginx configuration to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart
